### ISSUE TITLE
Add detailed replication statistics

### ISSUE THREAD

**Issue by dsamirov** [tarantool/stat#15]
Replication statistics is not clear enough. It should use instance's `host:port` instead of indexes.

For example:
```
info.replication.localhost:3301.lag: 0.00013041496276855
```
instead of
```
info.replication.1.lag: 0.00013041496276855
```

**Comment by Totktonada** [comment]
The module is [deprecated](https://github.com/tarantool/stat/commit/9b39a075ef59bc52754486511cb8cb44e46540f5) in favor of [metrics](https://github.com/tarantool/metrics). I'll close the issue.

If you still have a need that is not covered by default metrics in the metrics module, let us know: file an issue to metrics or reach us in the Telegram [chat](https://t.me/tarantool) (the Russian speaking chat is [here](https://t.me/tarantoolru)).
