### ISSUE TITLE
apt installation fail

### ISSUE THREAD

**Issue by d9k** [tarantool/stat#19]
```
% cat /etc/apt/sources.list.d/tarantool_1_10.list
deb http://download.tarantool.org/tarantool/1.10/ubuntu/ bionic main
deb-src http://download.tarantool.org/tarantool/1.10/ubuntu/ bionic main
```

```
% sudo apt install tarantool-stat
E: Unable to locate package tarantool-stat
```

**Comment by d9k** [comment]
Installation via luarocks works:

```
% cat ~/.luarocks/config-5.1.lua                 
rocks_servers = {
    [[http://rocks.tarantool.org]],
    [[https://rocks.moonscript.org]],
    -- default:
    -- [[https://luarocks.org]],
}
```

```
% luarocks install --local stat          
Installing http://rocks.tarantool.org/stat-scm-1.rockspec
. . . . . . .
```

**Comment by Totktonada** [comment]
The module is [deprecated](https://github.com/tarantool/stat/commit/9b39a075ef59bc52754486511cb8cb44e46540f5) in favor of [metrics](https://github.com/tarantool/metrics). I'll close the issue.

If there are installation problems with the metrics module, let us know: file an issue to metrics or reach us in the Telegram [chat](https://t.me/tarantool) (the Russian speaking chat is [here](https://t.me/tarantoolru)).
