### ISSUE TITLE
Replace instance_id in "replication.*" metrics to host:port

### ISSUE THREAD

**Issue by alexopryshko** [tarantool/stat#5]

**Comment by dedok** [comment]
Hi,

Can you describe your thoughts? I guess if you give an example, it will help a lot.

Thanks!

**Comment by Totktonada** [comment]
The module is [deprecated](https://github.com/tarantool/stat/commit/9b39a075ef59bc52754486511cb8cb44e46540f5) in favor of [metrics](https://github.com/tarantool/metrics). I'll close the issue.

If you still have a need that is not covered by default metrics in the metrics module, let us know: file an issue to metrics or reach us in the Telegram [chat](https://t.me/tarantool) (the Russian speaking chat is [here](https://t.me/tarantoolru)).
